# Generated by Django 5.1.15 on 2026-08-15 06:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TripRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passenger', models.CharField(blank=True, max_length=20)),
                ('load_kg', models.PositiveIntegerField(blank=True, null=True)),
                ('origin_name', models.CharField(max_length=200)),
                ('destination_name', models.CharField(max_length=200)),
                ('origin_lng', models.FloatField(blank=True, null=True)),
                ('origin_lat', models.FloatField(blank=True, null=True)),
                ('destination_lng', models.FloatField(blank=True, null=True)),
                ('destination_lat', models.FloatField(blank=True, null=True)),
                ('mode', models.CharField(blank=True, choices=[('comfort', '편안함'), ('sports', '스포티'), ('eco', '경제성')], max_length=10)),
                ('auto_recommend', models.BooleanField(default=True)),
                ('candidate_count', models.PositiveIntegerField(default=0)),
                ('recommended_route_id', models.CharField(blank=True, max_length=40)),
                ('selected_route_id', models.CharField(blank=True, max_length=40)),
                ('distance_km', models.FloatField(blank=True, null=True)),
                ('duration_min', models.FloatField(blank=True, null=True)),
                ('toll', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trips', to='users.driverprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TripFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField()),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trip', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='trips.triprecord')),
            ],
        ),
    ]
