# Generated by Django 5.1.15 on 2026-08-15 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='triprecord',
            name='preference_axis',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
